#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups


# shortcut for deleting things
del () {
    if [ -f "$1" ]
    then
        rm -fv "$1"
    else
        rm -rfv "$1"
    fi
}

# detach this (behaves like unlink)
del "$PROJECTR_FOLDER/home/.cache/nix"

# the usual things
del "$PROJECTR_FOLDER/.cache"
for item in $(find "$PROJECTR_FOLDER" -iregex '.*\.cleanable(\..*)?')
do
    del "$item"
done
mkdir -p "$PROJECTR_FOLDER/.cache" && touch "$PROJECTR_FOLDER/.cache/.keep" # restore the keep file

# remove git's hooks
if [[ -d "$PROJECTR_FOLDER/.git/hooks" ]]
then
    for file in $(find "$PROJECTR_FOLDER/.git/hooks")
    do
        # check if file exists
        if [ -f "$file" ]
        then
            rm -fv "$file"
        fi
    done
fi
